# axios


## 真实axios示例

真实axios拦截器如下所示
- 在真实请求axios之前，进行request的拦截
- 在真实请求axios之后，进行response的拦截

```javascript
axios.interceptors.request.use(function (config) {
    return config;
}, function (error) {
    return Promise.reject(error);
});

axios.interceptors.response.use(function (response) {
    return response;
}, function (error) {
    return Promise.reject(error);
});
```

## 分析拦截器实现原理

从上面的示例很容易就可以看出，`use(xxx)`跟`Promise.then(resolve, reject)`的原理很类似，我们可以直接通过
```javascript
const promise = Promise.resolve(config);

const promise1 = promise.then(()=> config);
const promise2 = promise1.then(()=> config);
```
链式调用不断执行每一个方法，然后返回对应的结果

## 手写axios拦截器

```javascript
const axios = function (config) {
    // 执行ajax请求
    console.warn("axios触发！");
    return {code: 0, message: "成功"};
}

axios.interceptors = {
    request: {
        data: []
    },
    response: {
        data: []
    }
}
axios.interceptors.request.use = (fn, fn1) => {
    axios.interceptors.request.data.push({
        resolved: fn,
        rejected: fn1
    });
}
axios.interceptors.response.use = (fn, fn1) => {
    axios.interceptors.response.data.push({
        resolved: fn,
        rejected: fn1
    });
}

axios.run = (config) => {
    let chain = [{
        resolved: axios,
        rejected: undefined
    }];

    const requestArray = axios.interceptors.request.data;
    // 真实axios的拦截器是倒序的，即request2->request1->axios->response1->response2
    for (let i = 0; i < requestArray.length; i++) {
        const item = requestArray[i];
        chain.unshift(item);
    }

    const responseArray = axios.interceptors.response.data;
    for (let i = 0; i < responseArray.length; i++) {
        const item = responseArray[i];
        chain.push(item);
    }

    let promise = Promise.resolve(config);
    let i = 0;
    while (i < chain.length) {
        const {resolved, rejected} = chain[i];
        promise = promise.then(resolved, rejected);
        i++;
    }

    chain = [];
    return promise;
}


axios.interceptors.request.use(function (config) {
    console.log("interceptors request1 触发");
    return config;
}, function (error) {
    console.error("interceptors request1 error触发");
    return Promise.reject(error);
});

axios.interceptors.request.use(function (config) {
    console.log("interceptors request2 触发");
    return config;
}, function (error) {
    console.error("interceptors request2 error触发");
    return Promise.reject(error);
});

axios.interceptors.response.use(function (response) {
    console.log("interceptors response1 触发");
    return response;
}, function (error) {
    console.error("interceptors response1 error触发");
    return Promise.reject(error);
});

axios.interceptors.response.use(function (response) {
    console.log("interceptors response2 触发");
    return response;
}, function (error) {
    console.error("interceptors response2 error触发");
    return Promise.reject(error);
});

axios.run({
    test: 1
}).then(res => {
    console.warn("最终请求返回结果是", res);
}).catch(error => {
    console.error("最终请求返回结果error是", error);
});
```

最终执行结果为：

```javascript
interceptors request2 触发
interceptors request1 触发
axios触发！
interceptors response1 触发
interceptors response2 触发
最终请求返回结果是 {code: 0, message: '成功'}
```

## 手写ajax
> 补充完整axios真正请求部分的逻辑代码



                    